### ISSUE TITLE
Compléter la fiche de personnage pdf

### ISSUE THREAD

**Issue by KevinPolez** [eveoniris/larpManager-php#16]
Pour le moment, la génération de la fiche de personnage n'indique que le nom du personnage, il faut y ajouter les compétences (et leur description), l'age, les points d'expérience, et toutes autres informations liés au personnage.

Le système de génération de pdf est déjà en place, il faut "juste" compléter la fiche.

**Comment by JosefRDA** [comment]
Ok pour me charger de celle là, c'est un bon exemple pour explorer le modèle de données joueurs.
