### ISSUE TITLE
[Admin] Revoir les résultats de recherche pour y ajouter des colonnes de tris

### ISSUE THREAD

**Issue by ErenHistarion** [eveoniris/larpManager-php#185]
Il faudrait que les pages type https://larpmanager.eveoniris.com/magie/sort/32/personnages ressemble à https://larpmanager.eveoniris.com/personnage/admin/list et que https://larpmanager.eveoniris.com/personnage/admin/list puisse faire du tri sur plus de colonnes.

**Comment by DarkAurore** [comment]
tu parles bien de tri et non de filtre ?
![image](https://user-images.githubusercontent.com/81388752/156899446-8b0d8fe9-24ea-4b1a-9783-1aa8be81edf8.png)
ce serait sur ces colonnes ci ? faut il aussi le faire sur la colonne utilisateur et dans ce cas là se baser sur quoi... ? le contenu avec les groupes + noms. et pour l'expérience, il faut trier simplement sur le nombre de points, peu importe le total ?

**Comment by ErenHistarion** [comment]
Du tri oui. :)

Pugilat et Héroïsme oui. 

Utilisateur on s'en fiche un peu comme tri, pareil pour les anomalies, c'est juste à titre informatif.

Merci

**Comment by DarkAurore** [comment]
ok alors du coup par contre pour info comme ce sont des champs qui ne sont pas stockés directement en base et qu'on ne va pas les recalculer à la volée en sql (enfin... on pourrait mais bon, bonjour les complications pour la requête ^^) cela sera moins performant que les autres colonnes, c'est à dire que j'applique le tri sur un + grand nombre de résultats côté sql et je refais le filtre sur la portion des résultats qui m'intéressent ensuite. 
mais ça fonctionne hein. juste un peu + lent forcément.

pour cette partie là c'est quasi fini.
par contre, en ce qui concerne appliquer cette "vue" pour les autres pages, l'idéal serait d'utiliser le même composant pour éviter de dupliquer du code.
donc ça nécessite un peu + de réflexion je pense... 
mais déjà au niveau de ton besoin, est-ce que tu veux juste le même tableau avec ces colonnes ou également :
- la possibilité de faire le tri
- la pagination
- les filtres de recherche

Et pourrais tu préciser toutes les pages sur lesquelles il faudrait l'appliquer en dehors des sorts ? (ouais c'est ptet long dsl mais comme je connais pas bien les fonctionnalités du site ça m'évitera de chercher partout ^^)

En bonus pour info j'ai revu au passage le filtre sur le nom pour utiliser un paramètre dans la requête et comme ça normalement pas besoin de la regex, ça suffira pour protéger des attaques d'injection.

**Comment by ErenHistarion** [comment]
Voici ce que j'ai en tête pour les pages où il faudrait améliorer la liste des joueurs :
/technologie/3/personnages
/magie/sort/1/personnages
/magie/priere/3/personnages
/magie/potion/1/personnages

Merci.
