### ISSUE TITLE
[Admin] Ajouter un statut PNJ au personnage

### ISSUE THREAD

**Issue by ErenHistarion** [eveoniris/larpManager-php#207]
Actuellement, il n'existe que 2 statuts Vivant et Mort, ce qui ne permet pas de distinguer un PJ d'un PNJ qui se cachent parfois au milieu d'un groupe.

En tant que scénariste, ça pourrait être utile de voir PNJ à la place de Vivant sur la fiche d'un personnage. Le statut Mort se fiche un peu plus de savoir si c'était un PJ ou un PNJ.

Dans les résultats de recherche, on pourrait peut être aussi penser à une icône spécifique pour les PNJ.

⚔️ : Vivant (PJ)
🎭 : PNJ
💀 : Mort

**Comment by DarkAurore** [comment]
alors si j'ai bien compris d'après le doc de référence BDD et un peu de check en base de mon côté  
- un personnage a un champ booléen "vivant" et a un "group_id"
- c'est via le groupe que l'on peut savoir si c'est un PNJ ou non, d'après le champ booléen "pj" du groupe.

seulement, il pourrait y avoir un personnage PNJ intégré à un groupe PJ de manière "cachée", est-ce qu'il y a un exemple de comment cela se traduit en base ou via l'interface pour ajouter un PNJ également dans un groupe PJ ? je me demande juste comment ce serait géré

**Comment by DarkAurore** [comment]
correction : en fait le statut pnj vient du billet qui a pour label 'Inscription PNJ' ou 'Gratuit PNJ' (d'ailleurs une condition contient PNJ serait ptet + flexible)
participant->billet->label 'pnj'
un personnage a une liste de participants (j'imagine que normalement c'est un participant par gn) et je suppose même que le perso peut être joué à un GN par un PJ et à un autre GN par un PNJ dans de rares cas même si ça doit pas être la norme.
dans tous les cas on peut se baser juste sur le dernier participant lié au perso.
pour moi on a donc déjà l'info, on peut la rajouter en +, à côté de Vivant, et oui on peut mettre aussi une icone PNJ pour la recherche mais je propose bien de rajouter cette information en + et conserver vivant / mort également.
