### ISSUE TITLE
Ajouter les éléments necessaires à la cnil

### ISSUE THREAD

**Issue by KevinPolez** [eveoniris/larpManager-php#21]
Il est obligatoire de mettre en avant les éléments nécessaires à la cnil afin de faire les choses dans les règles.

Voici quelques éléments résumé :

- préciser qui a accès aux données, et quel usage en sera fait.
- les données ont une date de péremption. Préciser lorsqu'elles seront supprimées
- préciser l'identité du responsable, la finalité de cette collecte d'information, l'aspect obligatoire ou facultatif, les transmissions envisagés
- autorisation de la cnil
- la collecte d'information doit être cohérente avec l'objectif suivis.

et une page récapitulative :

http://www.cnil.fr/vos-obligations/vos-obligations/

**Comment by jglafkid** [comment]
il faut que je fasse une déclaration simplifiée 


Le 3 nov. 2015 à 09:45, KevinPolez <notifications@github.com> a écrit :

Il est obligatoire de mettre en avant les éléments nécessaires à la cnil afin de faire les choses dans les règles.

Voici quelques éléments résumé :

préciser qui a accès aux données, et quel usage en sera fait.
les données ont une date de péremption. Préciser lorsqu'elles seront supprimées
préciser l'identité du responsable, la finalité de cette collecte d'information, l'aspect obligatoire ou facultatif, les transmissions envisagés
autorisation de la cnil
la collecte d'information doit être cohérente avec l'objectif suivis.
et une page récapitulative :

http://www.cnil.fr/vos-obligations/vos-obligations/
