### ISSUE TITLE
Gestion de l'age

### ISSUE THREAD

**Issue by ErenHistarion** [eveoniris/larpManager-php#231]
/age/

Faire apparaitre les âges par ordre d'id. (le plus jeune en haut, le plus vieux en bas)

PersonnageController.php

Il semble y avoir un bug dans la fonction vieillirAction() qui fait mourir prématurément les personnages. 
La règle c'est
- En vieillissant, tout le monde prend 1 token de vieillissement.
- Si on arrive à un nombre paire, >0, de token de vieillisement, on augmente la catérogie d'age de 1.
- Si $personnage->getAge()->getId() > 5, il meurt de vieillesse.

**Comment by Gerald-Arawn** [comment]
$personnage->getAge()->getId() ne peut pas être supérieur à 5, 5(vieux) étant la plus haute Id dans la table âge. Il faudrait, selon moi, une Id 6 (mort), pour que la fonction donne un résultat correct (en modifiant le code qui effectivement fait mourir les vieux actuellement, monde barbare).

**Comment by ErenHistarion** [comment]
> $personnage->getAge()->getId() ne peut pas être supérieur à 5, 5(vieux) étant la plus haute Id dans la table âge. Il faudrait, selon moi, une Id 6 (mort), pour que la fonction donne un résultat correct (en modifiant le code qui effectivement fait mourir les vieux actuellement, monde barbare).

C'est ce que j'ai fait en production et en local chez moi.

Mais ça a provoqué de nombreuses morts prématurées que je n'explique par pour l'instant.
