### ISSUE TITLE
[Impression personnage] Ajouter une partie "découpable".

### ISSUE THREAD

**Issue by ErenHistarion** [eveoniris/larpManager-php#275]
Comme pour la partie "Mort" à découper en bas de fiche, en ajouter une pour la partie Magie.

Pour la magie, l'un des moyens de diminuer le cout est de ponctionner de l'énergie vitale sur qqun de consentant ou pas.

Je te propose de faire ca en bas de page, sous la partie à découper quand on est mort, sur le même  principe,  en indiquant que si cette partie venait à être détachée, le personnage serait au mieux à l'état Blessé jusqu'à la fin du GN, sans qu'une quelconque compétence ne puisse le faire revenir à l'état de parfaite santé.

On peut y indiquer un score sur cette partie, qui peut être variable en fonction des pj.
Le score de base est de 1.
On doit pouvoir rajouter une case qui l'incrémente de 1 par exemple par le scénariste pour des personnages spéciaux avec du sang "divin" ou magique.
On ajoute également + 1 par niveau de magie. (Ca donnera de la pression pour que certains mages fassent une "chasse" contre les autres mages pour récupérer leur puissance, ca donnera du jeu et de la tension et ca me semble cohérent avec l'univers sombre.)

**Comment by TyliaPwet** [comment]
Salut Kevin,
Suite à la réunion de we dernier, il est probable qu'on te demande d'indiquer aussi le numéro de personnage sur la partie détachable ; si tu veux le faire avant de livrer du coup....

**Comment by ErenHistarion** [comment]
C'est déjà la cas. :)

**Comment by ErenHistarion** [comment]
En attente que les règles soient figées.
