### ISSUE TITLE
Layout de la page d'affichage des groupes bancale

### ISSUE THREAD

**Issue by Tsht** [eveoniris/larpManager-php#67]
La page d’affichage de groupe (https://larpmanager.eveoniris.com/gn/5/groupes) laisse apparaître parfois trop de descriptions, avec une mise en page qui “casse” l’affichage (pas beau les copier/coller de Word dans le Larp).

**Comment by ErenHistarion** [comment]
Il faudrait peut être juste nettoyer le texte importé depuis Word qui ajoute des tonnes de balise qui peuvent "casser" l'affichage.
