### ISSUE TITLE
[Admin] Recherche de personnage : seule le groupe LH2 apparaît

### ISSUE THREAD

**Issue by Tsht** [eveoniris/larpManager-php#69]
(https://larpmanager.eveoniris.com/personnage/admin/list) : Seul le groupe du LH2 apparaît dans le résultat de la recherche. Si le personnage a été créé après le LH2, son groupe n'apparaît pas dans l’interface.

**Comment by ErenHistarion** [comment]
Voir si la PR #123 règle le soucis.
