### ISSUE TITLE
[Admin] Gestion de l'âge avec les Fruits & Légumes

### ISSUE THREAD

**Issue by Tsht** [eveoniris/larpManager-php#74]
Avec les fruits et légumes, le personnage ne vieillit pas entre 2 GN, ou perd 5 ans, ou perd 1 token vieillesse, à voir le plus simple.
Gestion des l’année de jeu 1316, 1317 ou 1318 pour reporter le vieillissement sur les personnages.

**Comment by Tsht** [comment]
Honnêtement je pense que le token est le plus simple, avec un trigger en cas de mort vieillesse pour validation orga

**Comment by ErenHistarion** [comment]
Je pense également qu'ajouter dans le menu Technique de la page d'édition d'un personnage (https://larpmanager.eveoniris.com/personnage/admin/2/detail) un lien pour dire A consommer ses Fruits & Légumes pour supprimer un token de vieillesse est une bonne solution.

Penser à ajouter une ligne dans la chronologie du personnage : https://github.com/eveoniris/larpManager-php/issues/156

**Comment by ErenHistarion** [comment]
Voilà, à la suppression d'un token, ça ajoute dans la chronologie la consommation de Fruits et Légumes et ça recalcule la catégorie d'age ainsi que l'age réel du personnage.
