### ISSUE TITLE
[Impression] Enveloppe personnage : affiche tous les personnages secondaires de chaque LH

### ISSUE THREAD

**Issue by Tsht** [eveoniris/larpManager-php#79]
https://larpmanager.eveoniris.com/personnage/1/enveloppe/print : N'avoir que le dernier choix de personnage secondaire, pas la liste depuis les premiers LH.

**Comment by ErenHistarion** [comment]
Marche correctement sur la fiche d'impression de groupe : https://larpmanager.eveoniris.com/groupe/1/print/materiel/groupe

**Comment by ErenHistarion** [comment]
Je n'arrive pas à le reproduire en local, et je ne crois pas avoir vu de différence entre ce qu'il y a en prod et ce qu'on a dans la branche master. Peut être une différence entre master et developp ?

**Comment by Tsht** [comment]
Tu peux aussi tester sur le serveur de qualif d'orion, il reproduit le master
