### ISSUE TITLE
[Impression] Enveloppe personnage : spécification du dieu tutélaire pour la prétrise

### ISSUE THREAD

**Issue by Tsht** [eveoniris/larpManager-php#81]
https://larpmanager.eveoniris.com/personnage/1/enveloppe/print : Pour la compétence Prêtrise, faire apparaitre le nom du dieu tutélaire. Le dieu est (normalement) le seul au niveau Fervent ou Fanatique du personnage.

**Comment by TyliaPwet** [comment]
Ok le dieu principal est bien rajouté sur l'enveloppe. Du coup je pense qu'il n'est pas utile de laisser la mention entre parenthèses " (voir fiche de perso pour la divinité) "
De plus, si le contenu de la page /personnage/admin/xxxx/detail , section "Enveloppe" est un aperçu de ce qui va être imprimé, l'ajout de la divinité principale ne devrait-il pas être fait là aussi? ainsi que la suppression de la mention entre parenthèses
