### ISSUE TITLE
[Impression] Enveloppe personnage : compétence Mage n'affiche que Apprenti

### ISSUE THREAD

**Issue by Tsht** [eveoniris/larpManager-php#82]
https://larpmanager.eveoniris.com/personnage/1/enveloppe/print : Seule la compétence Magie (Apprenti) apparait, quel que soit le niveau de Magie possédé par le personnage.

**Comment by ErenHistarion** [comment]
Not a bug, en fait c'est qu'il n'y a que la Magie (Apprenti) qui apporte du matériel en jeu. D'où la confusion.
